MSG before call to bar
EVENT EXCEPTION terminate called with exception foo::exception: Oh that went badly
FAIL tnexcept.uncaught_exception
MSG before call to bar, in try block
MSG caught exception: Oh that went badly
PASS tnexcept.caught_exception
EXIT 1
